# autogenerated by txs
#include:etoolbox
#include:ltxdockit
\bibfield{arg1}#S
\bibtype{arg1}#S
\do#S
\fielditem#S
\listitem#S
\optitem#S
\reqitem#S
\typeitem#S
\begin{fieldlist}
\begin{typelist}
\end{fieldlist}
\end{typelist}
etoolbox.sty#S
ltxdockit.sty#S
