# autogenerated by txs
\CiteMoveChars#S
\OverciteFont#S
\citedash#S
\citeform#S
\citeleft#S
\citemid#S
\citenum#S
\citeonline#S
\citepunct#S
\citeright#S
\expandafter#S
\citemidpenalty#S
\citen #S
\citen#S
\citeprepenalty#S
\citepunctpenalty#S
\nocite #S
\nocitecount#S
