# autogenerated by txs
\dayofweeknameidenglish{arg1}#S
\monthnameenglish{arg1}#S
\ordinaldateenglish{arg1}#S
\shortdayofweeknameidenglish{arg1}#S
\shortmonthnameenglish{arg1}#S
\\monthnameenglish#S
\\shortmonthnameenglish#S
