# autogenerated by txs
#include:fontaxes
#include:fontenc
#include:fontspec
#include:ifluatex
#include:ifxetex
#include:mweights
#include:textcomp
#include:xkeyval
#include:xkeyval
\firamonofamily#S
\firamonolining#S
\firamonomedium#S
\firamonooldstyle#S
\sufigures#S
\ttdefault#S
