# autogenerated by txs
\MakeRobust{arg1}#S
\addpenalty{arg1}#S
\csname#S
\eminnershape#S
\setlength{arg1}#S
\( #S
\) #S
\TextOrMath #S
\TextOrMath#S
\[ #S
\] #S
\framebox #S
\makebox #S
\parbox #S
\raisebox #S
\rule #S
\savebox #S
\textsubscript #S
\textsubscript#S
