# autogenerated by txs
\disableindex{arg1}#S
\flushbottom#S
\index#S
\newindex#S
\printindex#S
\raggedbottom#S
\renewindex#S
\seename#S
\see{arg1}{arg2}#S
\see#S
ifproofmode#S
proofmodefalse#S
proofmodetrue#S
