# autogenerated by txs
\RSlargest#S
\RSpercentTolerance#S
\RSsmallest#S
\expandafter#S
\rs#S
\\larger #S
\\smaller #S
\\textlarger #S
\\textsmaller #S
\larger #S
\larger#S
\mathlarger #S
\mathlarger#S
\mathsmaller #S
\mathsmaller#S
\relscale #S
\relscale#S
\relsize #S
\relsize#S
\smaller #S
\smaller#S
\textlarger #S
\textlarger#S
\textscale #S
\textscale#S
\textsmaller #S
\textsmaller#S
